use std::collections::HashMap;
use std::fs::File;
use std::io::prelude::*;
use rand::Rng;
use serde_json::Value;
use reqwest;
use tokio;

const ARTICLE_TEXT: &str = r#"

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 2/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 3/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 4/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 5/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 6/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 7/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 8/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 9/55
✔ ✔ ✔
✔ ✔ ✔
✔ ✔ ✔
✔ ✔ ✔
✔ ✔ ✔
✔ ✔ ✔

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 10/55
𝔼(𝑆 −𝑆
𝑚𝑎𝑥 min⁡)

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 11/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 12/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 13/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 14/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 15/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 16/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 17/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 18/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 19/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 20/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 21/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 22/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 23/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 24/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 25/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 26/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 27/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 28/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 29/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 30/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 31/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 32/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 33/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 34/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 35/55
CRM Flesch Kincaid
Contract Type % %
2001 2022 2001 2022
Change Change
Non-Competes,
Confidentiality, - -
14.5 16.5 15.9 18.5
& Post- 13.80% 16.40%
Employment
Insurance,
- -
Indemnity, and 17 19.2 18.5 25.1
13.00% 35.50%
Coverage
Ownership,
-
Trust, and 16.5 18.1 -9.70% 18.9 23.2
23.30%
Governance
Mergers,
Alliance, and -
16.2 17.7 -9.30% 18.9 22.2
Investment 18.70%
Agreements
Shares, Stocks,
-
Incentives, and 15.6 17.2 -9.90% 17.4 19.3
10.90%
Options
Credit, Debt,
-
and Security 16.4 17.7 -7.90% 18.8 22.3
18.60%
Agreements
Property, -
16 17.2 -7.50% 18.1 20.9
Rights, and IP 15.50%
Purchase or
-
Sale 16.2 17.3 -6.80% 18.3 21
14.80%
Agreement
Settlement,
Waiver, and
16.6 17.6 -6.00% 19.3 20.9 -8.30%
Termination or
Severance
Employment
16.4 17.2 -4.90% 18.7 20 -7.00%
Agreement
Services &
15.3 15.2 -0.7% 16.5 17.4 -5.50%
Supply

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 36/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 37/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 38/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 39/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 40/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 41/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 42/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 43/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 44/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 45/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 46/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 47/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 48/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 49/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 50/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 51/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 52/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 53/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 54/55

<<PAGE_BREAK>>

ARBEL, THE READABILITY OF CONTRACTS: BIG DATA ANALYSIS 55/55"#;

fn main() {
    println\!("{}", ARTICLE_TEXT);
}